### ISSUE TITLE
StartEnclave failed. Error: The underlying platform or hardware returned an error. 

### ISSUE THREAD

**Issue by dabaizzt** [mc2-project/opaque-sql#216]
when i run `build/sbt test` , it gives the following error:
`Cause: edu.berkeley.cs.rise.opaque.OpaqueException: StartEnclave failed. Error: The underlying platform or hardware returned an error. For example, an SGX user-mode instruction failed.`

**Comment by octaviansima** [comment]
Hi @dabaizzt, can you provide some more information so we can help debug this? It looks like you're running into issues with the Open Enclave platform. Some things I would recommend:

- Ensure that all the [Open Enclave installation tasks](https://mc2-project.github.io/opaque/install/install.html) worked
- Try first running the [Open Enclave sample code](https://github.com/openenclave/openenclave/tree/master/samples/helloworld)

Also, are you running in simulation or hardware mode?

**Comment by dabaizzt** [comment]
Thank you for 

> Hi @dabaizzt, can you provide some more information so we can help debug this? It looks like you're running into issues with the Open Enclave platform. Some things I would recommend:
> 
> * Ensure that all the [Open Enclave installation tasks](https://mc2-project.github.io/opaque/install/install.html) worked
> * Try first running the [Open Enclave sample code](https://github.com/openenclave/openenclave/tree/master/samples/helloworld)
> 
> Also, are you running in simulation or hardware mode?

**Comment by dabaizzt** [comment]
Thank you for your kind reply。the result of running  [https://github.com/openenclave/openenclave/tree/master/samples/helloword](url) is ok，the results are shown in the figure below


<img width="794" alt="截屏2021-04-27 下午3 00 38" src="https://user-images.githubusercontent.com/20527360/116200512-00b2f700-a76b-11eb-9da1-19dc97905bc7.png">

After that, I tried to reinstall _Intel SGX DCAP Driver v1.41_ based on https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux，and I have added the current user _cqs_ to the group _sgx_prv_ through  `sudo usermod -a -G sgx_prv cqs` 。
However, when I run `build/sbt test,` the following error is reported：

> [error_driver2api sgx_enclave_common.cpp:249] Enclave not authorized to run, .e.g. provisioning enclave hosted in app without access rights to /dev/sgx_provision. You need add the user id to group sgx_prv or run the app as root.
[load_pce ../pce_wrapper.cpp:175] Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:4004.
21/04/27 15:03:27 ERROR Executor: Exception in task 2.0 in stage 1.0 (TID 5)
edu.berkeley.cs.rise.opaque.OpaqueException: OE report is NULL
	at edu.berkeley.cs.rise.opaque.execution.SGXEnclave.GenerateReport(Native Method)
	at edu.berkeley.cs.rise.opaque.Utils$.generateReport(Utils.scala:352)
	at edu.berkeley.cs.rise.opaque.RA$.$anonfun$initRA$2(RA.scala:54)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by octaviansima** [comment]
Hmm, I've never used that method of installing the SGX Driver. We use this for v1.36:
```
sudo apt update
sudo apt -y install dkms
wget https://download.01.org/intel-sgx/sgx-dcap/1.9/linux/distro/ubuntu18.04-server/sgx_linux_x64_driver_1.36.2.bin
chmod +x sgx_linux_x64_driver_1.36.2.bin
sudo ./sgx_linux_x64_driver_1.36.2.bin
rm -rf sgx_linux_x64_driver_1.36.2.bin
```

In the code, that error is being thrown during remote attestation, which is only enabled in hardware mode. Can you try doing `export MODE=SIMULATE` and let me know if you are still encountering issues with `build/sbt test`? It would be helpful to determine if this is an OE installation issue or something we need to look into on our end.

**Comment by dabaizzt** [comment]
I have tried `export MODE=SIMULATE` before `build/sbt test` ，the error is shown below:


> [info]   Cause: edu.berkeley.cs.rise.opaque.OpaqueException: Encrypt failed. Error: The function is unable to bind the current host thread to an enclave thread. This occurs when the host performs an **ECALL** while all enclave threads are in use.

**Comment by octaviansima** [comment]
We are working on a setup script to simplify the installation process for Opaque's dependencies -- we are fairly confident it's an issue with how Open Enclave was installed, since these errors were not reproducible when doing a clean install. In the meantime, I recommend going through the [installation docs](https://mc2-project.github.io/opaque/install/install.html) again and verifying that everything was done correctly. If you still can't build from source, you can experiment with the project by following the [quickstart](https://github.com/mc2-project/mc2#quickstart), which uses a Docker container with all dependencies pre-installed.

**Comment by octaviansima** [comment]
@dabaizzt we now have a script you can run with `source ./scripts/install.sh` that should install everything properly.
